version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: health_postgres
    environment:
      POSTGRES_DB: health_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  
      - "15672:15672" #   Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  pgadmin:
    image: dpage/pgadmin4
    container_name: health_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ziads5933@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ziadsalah
    ports:
      - "8080:80"                              
    depends_on:
      - postgres