version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: health_postgres
    environment:
      POSTGRES_DB: health_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
